import Head from "next/head";
import { useAuth } from "../config/AuthContext";
import styles from "../styles/Home.module.css";

export default function Signin(props) {
  const { authenticated, user, login, logout } = useAuth();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ul>
          <li>Authenticated: {authenticated}</li>
          <li>User: {user?.displayName}</li>
        </ul>
        <button onClick={login}>Signin</button>
      </main>
    </div>
  );
}
